const { withAppBuildGradle } = require('@expo/config-plugins');

const BUILD_TYPES_MARKER = '// @generated by with-android-customizations';

const BUILD_TYPES_APPLY = `${BUILD_TYPES_MARKER}
apply from: new File(
    rootDir,
    "../gradle/android-build-types.gradle",
)
`;

const withBuildGradleCustomizations = config =>
  withAppBuildGradle(config, config => {
    const { contents } = config.modResults;

    if (!contents.includes(BUILD_TYPES_MARKER)) {
      config.modResults.contents = `${contents.trimEnd()}

${BUILD_TYPES_APPLY}`;
    }

    return config;
  });

module.exports = withBuildGradleCustomizations;
